exclude: .*migrations\/.*
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.13
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/djlint/djLint
  rev: v1.36.4
  hooks:
    - id: djlint-django

- repo: https://github.com/python-poetry/poetry
  rev: '2.1.3'
  hooks:
    - id: poetry-export
      args: [
        "-f", "requirements.txt",
        "-o", "requirements.txt",
        "--without-hashes"
      ]

- repo: local
    hooks:
      - id: ty
        name: ty check
        entry: ty check .
        language: python
