FROM python:3.11

WORKDIR /app

ENV VIRTUAL_ENV=/app/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY pyproject.toml uv.lock ./
RUN pip install --upgrade pip && pip install --no-cache-dir uv
RUN uv sync --frozen --no-dev --no-install-project

COPY . .
