[project]
name = "ask_hn_digest"
version = "0.1.1"
description = "Get Summaries of the most engaging discussions on Hacker News"
authors = [{ name = "Rasul Kireev", email = "me@rasulkireev.com" }]
requires-python = ">=3.14,<4.0"
dependencies = [
    "aiohttp>=3.13.3",
    "asyncpg>=0.31.0",
    "croniter>=6.0.0",
    "django>=6.0.2",
    "django-anymail>=14.0",
    "django-environ>=0.12.0",
    "django-extensions>=4.1",
    "django-mjml>=1.5",
    "django-ninja>=1.5.3",
    "django-q2>=1.9.0",
    "django-storages>=1.14.6",
    "django-structlog>=10.0.0",
    "django-widget-tweaks>=1.5.1",
    "google-genai>=1.62.0",
    "gunicorn>=25.0.1",
    "ipython>=9.10.0",
    "logfire>=4.22.0",
    "markdown>=3.10.1",
    "mkdocstrings>=1.0.2",
    "nest-asyncio>=1.6.0",
    "pillow>=12.1.0",
    "posthog>=7.8.2",
    "psycopg2-binary>=2.9.11",
    "pydantic[email]>=2.12.5",
    "pytest>=9.0.2",
    "pytest-django>=4.11.1",
    "python-webpack-boilerplate>=1.0.4",
    "redis>=7.1.0",
    "requests>=2.32.5",
    "sentry-sdk>=2.52.0",
    "structlog>=25.5.0",
    "structlog-sentry>=2.2.1",
    "whitenoise>=6.11.0",
]

[dependency-groups]
dev = [
    "djlint>=1.36.4",
    "pre-commit>=4.5.1",
    "ruff>=0.15.0",
    "ty>=0.0.15",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "B",    # flake8-bugbear
    "I",    # isort
    "DJ",   # django-specific rules
    "UP",   # pyupgrade
    "C90",  # mccabe complexity
]

[tool.ruff.lint.per-file-ignores]
"**/migrations/*.py" = ["E501", "F401", "F403", "F405"]

[tool.ruff.format]
quote-style = "double"

[tool.djlint]
profile="django"
ignore = "H031,H006,H023,H021,H011,T002"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []
