# Generated by Django 5.2.1 on 2025-05-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='added_to_buttondown',
            field=models.BooleanField(default=False),
        ),
    ]
