# Generated by Django 5.2.1 on 2025-05-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hndiscussionsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='hndiscussionsummary',
            name='description',
            field=models.TextField(default=1, help_text='Description of the blog post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hndiscussionsummary',
            name='slug',
            field=models.SlugField(default='', help_text='Slug for the blog post', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hndiscussionsummary',
            name='title',
            field=models.CharField(default=None, help_text='Title of the blog post', max_length=250),
            preserve_default=False,
        ),
    ]
