# Generated by Django 5.2.1 on 2025-05-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hndiscussionsummary_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hndiscussionsummary',
            name='discussion_title',
            field=models.CharField(default=1, help_text='Title of the discussion', max_length=500),
            preserve_default=False,
        ),
    ]
