# Generated by Django 5.2.1 on 2025-05-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hndiscussionsummary_discussion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hndiscussionsummary',
            name='twitter_thread',
            field=models.TextField(blank=True),
        ),
    ]
