# Generated by Django 5.2.1 on 2025-01-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hndiscussionsummary_twitter_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='hndiscussionsummary',
            name='single_tweet',
            field=models.TextField(blank=True),
        ),
    ]
