# Generated by Django 5.2.1 on 2025-05-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hndiscussionsummary_twitter_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='hndiscussionsummary',
            name='summary_tags',
            field=models.TextField(blank=True, help_text='Tags for categorizing the discussion summary', null=True),
        ),
    ]
