# Generated by Django 5.2.2 on 2025-08-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_hndiscussionsummary_single_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='hndiscussionsummary',
            name='reddit_post',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hndiscussionsummary',
            name='subreddits',
            field=models.TextField(blank=True, help_text='Subreddits to post to'),
        ),
    ]
