# Generated by Django 5.2.9 on 2025-12-22 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hndiscussionsummary_reddit_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='hn_discussion_summary',
            field=models.ForeignKey(blank=True, help_text='Related Hacker News discussion summary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='core.hndiscussionsummary'),
        ),
    ]
