# Generated by Django 6.0.2 on 2026-05-22 12:46

import re
import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify

TAG_NAME_MAX_LENGTH = 80
TAG_SLUG_MAX_LENGTH = 96
TAG_SPLIT_RE = re.compile(r"[,;\n]+")
TAG_WHITESPACE_RE = re.compile(r"\s+")

CANONICAL_TAG_ALIASES = {
    "AI": ("artificial intelligence", "a i", "ai tools", "gen ai", "genai", "generative ai"),
    "AI Agents": ("agents", "agentic ai", "ai agent", "ai agents"),
    "APIs": ("api", "application programming interfaces"),
    "AR/VR": ("ar", "vr", "augmented reality", "virtual reality", "mixed reality", "xr"),
    "AWS": ("amazon web services",),
    "Business": ("business model", "business models"),
    "C": ("c programming", "ansi c"),
    "C++": ("cpp", "cplusplus", "c plus plus"),
    "CI/CD": ("ci cd", "cicd", "continuous integration", "continuous delivery"),
    "CSS": ("cascading style sheets",),
    "Databases": ("database", "db", "dbs"),
    "DevOps": ("dev ops", "developer operations"),
    "Developer Tools": ("dev tools", "devtools", "development tools"),
    "Docker": ("containers", "containerization"),
    "GPT": ("chatgpt", "gpt models", "gpts"),
    "Go": ("golang",),
    "HTML": ("hypertext markup language",),
    "JavaScript": ("js", "ecmascript"),
    "LLMs": ("llm", "large language model", "large language models"),
    "Machine Learning": ("ml", "machine-learning"),
    "Node.js": ("node", "nodejs"),
    "PostgreSQL": ("postgres", "postgresql", "psql"),
    "React": ("react.js", "reactjs"),
    "Ruby on Rails": ("rails", "ror"),
    "SaaS": ("software as a service",),
    "SQLite": ("sqlite3",),
    "TypeScript": ("ts",),
    "UI": ("user interface", "interfaces"),
    "UX": ("user experience",),
}

TAG_DISPLAY_OVERRIDES = {
    "ai": "AI",
    "api": "API",
    "apis": "APIs",
    "ar": "AR",
    "aws": "AWS",
    "cli": "CLI",
    "cpu": "CPU",
    "css": "CSS",
    "devops": "DevOps",
    "dns": "DNS",
    "gpu": "GPU",
    "gpt": "GPT",
    "html": "HTML",
    "ios": "iOS",
    "ip": "IP",
    "llm": "LLM",
    "llms": "LLMs",
    "macos": "macOS",
    "ml": "ML",
    "mysql": "MySQL",
    "nosql": "NoSQL",
    "postgresql": "PostgreSQL",
    "saas": "SaaS",
    "seo": "SEO",
    "sql": "SQL",
    "ui": "UI",
    "ux": "UX",
    "vr": "VR",
}

TAG_SLUG_OVERRIDES = {
    "C++": "c-plus-plus",
}

NOISY_TAG_SLUGS = {
    "ask-hn",
    "hacker-news",
    "hn",
    "news-ycombinator",
    "y-combinator-news",
}

LANE_KEYWORD_SLUGS = {
    "ai_ml": (
        "ai",
        "ai-agents",
        "chatgpt",
        "computer-vision",
        "embeddings",
        "generative-ai",
        "gpt",
        "llm",
        "llms",
        "machine-learning",
        "neural-network",
        "neural-networks",
        "nlp",
        "openai",
    ),
    "programming": (
        "algorithms",
        "c",
        "c-plus-plus",
        "coding",
        "compilers",
        "django",
        "go",
        "java",
        "javascript",
        "nodejs",
        "programming",
        "python",
        "rails",
        "react",
        "ruby",
        "ruby-on-rails",
        "rust",
        "software-engineering",
        "typescript",
        "web-development",
    ),
    "devtools_infra": (
        "api",
        "apis",
        "aws",
        "cicd",
        "cloud",
        "databases",
        "deployment",
        "developer-tools",
        "devops",
        "docker",
        "git",
        "infrastructure",
        "kubernetes",
        "linux",
        "monitoring",
        "observability",
        "postgresql",
        "sqlite",
    ),
    "startups_business": (
        "bootstrapping",
        "business",
        "fundraising",
        "marketing",
        "pricing",
        "sales",
        "saas",
        "startup",
        "startups",
    ),
    "careers_work": (
        "career",
        "careers",
        "hiring",
        "interviewing",
        "management",
        "productivity",
        "remote-work",
        "work",
    ),
    "security_privacy": (
        "cryptography",
        "privacy",
        "security",
        "surveillance",
    ),
    "product_design": (
        "design",
        "product",
        "product-management",
        "ui",
        "ux",
    ),
    "hardware_science": (
        "biology",
        "energy",
        "gpu",
        "hardware",
        "math",
        "physics",
        "science",
    ),
    "culture_society": (
        "culture",
        "education",
        "ethics",
        "law",
        "policy",
        "society",
        "writing",
    ),
}


def alias_lookup():
    lookup = {}

    for canonical_name in CANONICAL_TAG_ALIASES:
        alias_slug = slugify(canonical_name)
        if alias_slug:
            lookup.setdefault(alias_slug, canonical_name)

    for canonical_name, aliases in CANONICAL_TAG_ALIASES.items():
        for alias in aliases:
            alias_slug = slugify(alias)
            if alias_slug:
                lookup.setdefault(alias_slug, canonical_name)
    return lookup


CANONICAL_TAG_BY_ALIAS_SLUG = alias_lookup()


def clean_raw_tag_name(raw_tag):
    if raw_tag is None:
        return ""

    tag_name = str(raw_tag).strip().strip("\"'")
    tag_name = tag_name.removeprefix("#").strip()
    tag_name = tag_name.replace("_", " ")
    tag_name = TAG_WHITESPACE_RE.sub(" ", tag_name).strip(" .")
    return tag_name[:TAG_NAME_MAX_LENGTH].strip()


def display_tag_name(raw_name):
    words = []
    for word in raw_name.split(" "):
        word_slug = slugify(word)
        if word_slug in TAG_DISPLAY_OVERRIDES:
            words.append(TAG_DISPLAY_OVERRIDES[word_slug])
        elif word.isupper() and len(word) <= 5:
            words.append(word)
        else:
            words.append(word.capitalize())
    return " ".join(words).strip()


def normalize_tag_name(raw_tag):
    cleaned_name = clean_raw_tag_name(raw_tag)
    if not cleaned_name:
        return ""

    cleaned_slug = slugify(cleaned_name)
    if not cleaned_slug or cleaned_slug in NOISY_TAG_SLUGS:
        return ""

    for canonical_name in CANONICAL_TAG_ALIASES:
        if cleaned_name.casefold() == canonical_name.casefold():
            return canonical_name

    canonical_name = CANONICAL_TAG_BY_ALIAS_SLUG.get(cleaned_slug)
    if canonical_name:
        return canonical_name

    return display_tag_name(cleaned_name)


def canonical_tag_slug(tag_name):
    return TAG_SLUG_OVERRIDES.get(tag_name, slugify(tag_name))[:TAG_SLUG_MAX_LENGTH]


def is_exact_canonical_tag_name(tag_name):
    return any(tag_name.casefold() == canonical_name.casefold() for canonical_name in CANONICAL_TAG_ALIASES)


def infer_topic_lane(tag_name):
    tag_slug = slugify(tag_name)
    for lane, keyword_slugs in LANE_KEYWORD_SLUGS.items():
        for keyword_slug in keyword_slugs:
            if tag_slug == keyword_slug or tag_slug.startswith(f"{keyword_slug}-"):
                return lane
    return "other"


def get_or_create_tag(raw_name, Tag, TagAlias, db_alias):
    cleaned_name = clean_raw_tag_name(raw_name)
    canonical_name = normalize_tag_name(cleaned_name)
    if not canonical_name:
        return None

    raw_slug = slugify(cleaned_name)
    is_exact_canonical = is_exact_canonical_tag_name(cleaned_name)
    if raw_slug and not is_exact_canonical:
        alias = TagAlias.objects.using(db_alias).select_related("tag").filter(slug=raw_slug).first()
        if alias:
            return alias.tag

    tag_slug = canonical_tag_slug(canonical_name)
    tag, _created = Tag.objects.using(db_alias).get_or_create(
        slug=tag_slug,
        defaults={
            "name": canonical_name,
            "topic_lane": infer_topic_lane(canonical_name),
        },
    )

    inferred_lane = infer_topic_lane(canonical_name)
    if tag.topic_lane == "other" and inferred_lane != "other":
        tag.topic_lane = inferred_lane
        tag.save(update_fields=["topic_lane"])

    if raw_slug and not is_exact_canonical and raw_slug != tag.slug:
        TagAlias.objects.using(db_alias).get_or_create(
            slug=raw_slug[:TAG_SLUG_MAX_LENGTH],
            defaults={"tag": tag, "name": cleaned_name[:TAG_NAME_MAX_LENGTH]},
        )

    return tag


def backfill_normalized_tags(apps, schema_editor):
    HNDiscussionSummary = apps.get_model("core", "HNDiscussionSummary")
    Tag = apps.get_model("core", "Tag")
    TagAlias = apps.get_model("core", "TagAlias")
    db_alias = schema_editor.connection.alias

    for canonical_name, aliases in CANONICAL_TAG_ALIASES.items():
        tag = get_or_create_tag(canonical_name, Tag, TagAlias, db_alias)
        if not tag:
            continue
        for alias_name in aliases:
            alias_slug = slugify(alias_name)
            if alias_slug and alias_slug != tag.slug:
                TagAlias.objects.using(db_alias).get_or_create(
                    slug=alias_slug[:TAG_SLUG_MAX_LENGTH],
                    defaults={"tag": tag, "name": alias_name[:TAG_NAME_MAX_LENGTH]},
                )

    through = HNDiscussionSummary.tags.through
    relations = []
    relation_keys = set()

    summaries = HNDiscussionSummary.objects.using(db_alias).exclude(legacy_tags="").iterator()
    for summary in summaries:
        for raw_tag in TAG_SPLIT_RE.split(summary.legacy_tags):
            tag = get_or_create_tag(raw_tag, Tag, TagAlias, db_alias)
            if not tag:
                continue
            relation_key = (summary.id, tag.id)
            if relation_key in relation_keys:
                continue
            relation_keys.add(relation_key)
            relations.append(
                through(
                    hndiscussionsummary_id=summary.id,
                    tag_id=tag.id,
                )
            )

    if relations:
        through.objects.using(db_alias).bulk_create(relations, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hndiscussionsummary_reddit_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=96, unique=True)),
                ('topic_lane', models.CharField(choices=[('ai_ml', 'AI & Machine Learning'), ('programming', 'Programming'), ('devtools_infra', 'Dev Tools & Infrastructure'), ('startups_business', 'Startups & Business'), ('careers_work', 'Careers & Work'), ('security_privacy', 'Security & Privacy'), ('product_design', 'Product & Design'), ('hardware_science', 'Hardware & Science'), ('culture_society', 'Culture & Society'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
            ],
            options={
                'ordering': ['topic_lane', 'name'],
            },
        ),
        migrations.RenameField(
            model_name='hndiscussionsummary',
            old_name='tags',
            new_name='legacy_tags',
        ),
        migrations.AlterField(
            model_name='hndiscussionsummary',
            name='legacy_tags',
            field=models.TextField(blank=True, help_text='Original comma-separated tags for this post'),
        ),
        migrations.CreateModel(
            name='TagAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=96, unique=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.tag')),
            ],
            options={
                'verbose_name_plural': 'tag aliases',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hndiscussionsummary',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='summaries', to='core.tag'),
        ),
        migrations.RunPython(backfill_normalized_tags, migrations.RunPython.noop),
    ]
